# Base image
FROM python:3.10-slim

# Working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the pipeline code and credentials
COPY dlt_ingestion/ /app

# Environment variable for GCP creds
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/keys/bq_service_account.json

# Run the pipeline script
CMD ["python", "pipeline.py"]
