version: 2

sources:
  - name: staging  # This should match the dataset in BigQuery
    database: acoustic-env-454618-v3  # Replace with your actual GCP project ID
    schema: covid_raw_data  # This should match your dataset in BigQuery
    tables:
      - name: vaccination_data_raw  # This should match your table in BigQuery


models:
  - name: stg_vaccination_data_raw
    description: ""
    columns:
      - name: location
        data_type: string
        description: ""
        tests:
          - not_null:
              severity: warn
         

      - name: iso_code
        data_type: string
        description: ""
        tests:
          - not_null:
              severity: warn

      - name: vaccination_date
        data_type: string
        description: ""

      - name: day
        data_type: int64
        description: ""

      - name: quarter
        data_type: int64
        description: ""

      - name: year
        data_type: int64
        description: ""

      - name: total_vaccinations
        data_type: float64
        description: ""

      - name: people_vaccinated
        data_type: float64
        description: ""

      - name: people_fully_vaccinated
        data_type: float64
        description: ""

      - name: total_boosters
        data_type: float64
        description: ""

      - name: daily_vaccinations_raw
        data_type: float64
        description: ""

      - name: daily_vaccinations
        data_type: float64
        description: ""

      - name: total_vaccinations_per_hundred
        data_type: float64
        description: ""

      - name: people_vaccinated_per_hundred
        data_type: float64
        description: ""

      - name: people_fully_vaccinated_per_hundred
        data_type: float64
        description: ""

      - name: total_boosters_per_hundred
        data_type: float64
        description: ""

      - name: daily_vaccinations_per_million
        data_type: float64
        description: ""

      - name: daily_people_vaccinated
        data_type: float64
        description: ""

      - name: new_vaccinated
        data_type: float64
        description: ""

      - name: daily_people_vaccinated_per_hundred
        data_type: float64
        description: ""