
version: 2

models:
  - name: fact_ten_top_vaccination_countries
    description: ""
    columns:
      - name: country_name
        data_type: string
        description: ""

      - name: country_id
        data_type: string
        description: ""

      - name: year
        data_type: int64
        description: ""

      - name: people_vaccinated
        data_type: float64
        description: ""

      - name: total_vaccinations
        data_type: float64
        description: ""

      - name: people_fully_vaccinated
        data_type: float64
        description: ""

      - name: total_boosters
        data_type: float64
        description: ""

      - name: daily_vaccinations
        data_type: float64
        description: ""

      - name: daily_vaccinations_raw
        data_type: float64
        description: ""

      - name: total_vaccinations_per_hundred
        data_type: float64
        description: ""

      - name: people_vaccinated_per_hundred
        data_type: float64
        description: ""

      - name: people_fully_vaccinated_per_hundred
        data_type: float64
        description: ""

      - name: total_boosters_per_hundred
        data_type: float64
        description: ""

      - name: daily_vaccinations_per_million
        data_type: float64
        description: ""

      - name: daily_people_vaccinated
        data_type: float64
        description: ""

      - name: daily_people_vaccinated_per_hundred
        data_type: float64
        description: ""

      - name: rank
        data_type: int64
        description: ""

  - name: fact_aggregation
    description: ""
    columns:
      - name: vaccination_fact_id
        data_type: int64
        description: ""

      - name: location
        data_type: string
        description: ""

      - name: year
        data_type: int64
        description: ""

      - name: total_vaccinations
        data_type: float64
        description: ""

      - name: people_vaccinated
        data_type: float64
        description: ""

      - name: people_fully_vaccinated
        data_type: float64
        description: ""

      - name: total_boosters
        data_type: float64
        description: ""

      - name: daily_vaccinations
        data_type: float64
        description: ""

      - name: daily_vaccinations_raw
        data_type: float64
        description: ""

      - name: total_vaccinations_per_hundred
        data_type: float64
        description: ""

      - name: people_vaccinated_per_hundred
        data_type: float64
        description: ""

      - name: people_fully_vaccinated_per_hundred
        data_type: float64
        description: ""

      - name: total_boosters_per_hundred
        data_type: float64
        description: ""

      - name: daily_vaccinations_per_million
        data_type: float64
        description: ""

      - name: daily_people_vaccinated
        data_type: float64
        description: ""

      - name: daily_people_vaccinated_per_hundred
        data_type: float64
        description: ""

  - name: dim_population
    description: ""
    columns:
      - name: name
        data_type: string
        description: ""

      - name: total_population
        data_type: int64
        description: ""

  - name: dim_country_code
    description: ""
    columns:
      - name: name
        data_type: string
        description: ""

      - name: gec
        data_type: string
        description: ""

      - name: alpha_3_code
        data_type: string
        description: ""

      - name: iso_code
        data_type: string
        description: ""

      - name: alpha_2_code
        data_type: string
        description: ""

      - name: num
        data_type: string
        description: ""

  - name: fact_population_vaccinated
    description: ""
    columns:
      - name: vaccination_fact_id
        data_type: int64
        description: ""

      - name: name
        data_type: string
        description: ""

      - name: year
        data_type: int64
        description: ""

      - name: people_vaccinated
        data_type: float64
        description: ""

      - name: total_population
        data_type: int64
        description: ""

      - name: percentage_vaccinated
        data_type: float64
        description: ""
